# Generated by Django 3.2.5 on 2021-07-22 00:23

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210722_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date_occuring',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='org_email',
            field=models.EmailField(default='none', max_length=254),
            preserve_default=False,
        ),
    ]
